apiVersion: v1
kind: Service
metadata:
  name: beanie-genie
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.104
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: beanie-genie
  type: LoadBalancer
